### Get all invoices

GET http://localhost:5100/invoices
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJqYWt1YkBwcmlzbWEuaW8iLCJpYXQiOjE2NjQ5NzIzMTIsImV4cCI6MTY2NTA1ODcxMn0.H1MdQd7pDwpyBXGyPM4woHNFcK7UpwEX9yEDjnT1tvA

### Get invoice by id

GET http://localhost:5100/invoices/2
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJqYWt1YkBwcmlzbWEuaW8iLCJpYXQiOjE2NjQ5NzIzMTIsImV4cCI6MTY2NTA1ODcxMn0.H1MdQd7pDwpyBXGyPM4woHNFcK7UpwEX9yEDjnT1tvA
